version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
     - 4317:4317
     - 16686:16686
    environment:
     - COLLECTOR_OTLP_ENABLED=true
  proxy:
    image: vjuranek/counter-proxy
    build:
      context: counter-proxy
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
     - 8080:8080
  counter:
    image: vjuranek/counter
    build:
      context: counter
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
       - 8081:8080
